# Generated by Django 4.1.3 on 2022-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('junaeb', models.CharField(help_text='Ingrese Si o No posee pago Junaeb', max_length=5)),
                ('vegano', models.CharField(help_text='Ingrese Si o No posee menu vegano', max_length=5)),
                ('imagen', models.ImageField(null=True, upload_to='locales')),
                ('latitud', models.DecimalField(decimal_places=30, max_digits=30)),
                ('longitud', models.DecimalField(decimal_places=30, max_digits=30)),
                ('veggie', models.CharField(max_length=5)),
            ],
        ),
    ]
